[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    dfrobot/DFRobotDFPlayerMini
build_src_filter =
    +<sentrylab_audio_alarm.ino>
